[package]
name = "qrusty"
version = "0.1.0"
authors = ["patchispatch <juanov98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
